name = "playground"
defaultTargets = ["proofs"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.21.0"

[[lean_lib]]
name = "proofs"
